name: Build Android APK with EAS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set working directory to Demo
      #   working-directory: Demo
      #   run: echo "Working in ./Demo"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Demo/package-lock.json

          
      - name: Install dependencies
        working-directory: Demo
        run: npm install --legacy-peer-deps

      - name: Install EAS CLI globally
        run: npm install -g eas-cli --legacy-peer-deps

      - name: Run EAS Build (Android)
        working-directory: Demo
        run: eas build --platform android --profile development --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
