name: Node.js Jest Unit Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: Demo/package-lock.json

      - name: Install dependencies
        working-directory: Demo
        run: npm install --legacy-peer-deps

      - name: Build the project (if applicable)
        working-directory: Demo
        run: npm run build --if-present

      - name: Run tests
        working-directory: Demo
        run: npm test
